### ISSUE TITLE
BUG: Seperate issue tracker available

### ISSUE THREAD

**Issue by cstruct** [LinusU/monofile#1]
I recently noticed a probable bug with `monofile`, issue tracking is available outside the file.

The expected behavior is storing issue tracking as meta-data in the `monofile`.

I will submit a PR for correcting this.

**Comment by LinusU** [comment]
:joy: :joy: this is awesome!

**Comment by cstruct** [comment]
Since the repository is still empty I can not create a PR. 

What i realized though is that a PR in Github is just as wrong as issues. This should be staged in the monofile as well. 

[Disabling issues](https://help.github.com/articles/disabling-issues/)
